language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install pytz timeout_decorator
  - pip install oslo.messaging
services:
  - rabbitmq
notifications:
  email: user.localhost2000@gmail.com
script: python -m unittest discover tests --pattern=*.py
